/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'James' at '3/3/16 11:20 AM' with Gradle 2.11
 *
 * @author James, @date 3/3/16 11:20 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
